const exampleData = [{
  name: 'Dom Perignon Champagne Cuvee Vintage',
  code: 'dom-perignon-champagne-cuvee-vintage-2005',
  region: 'France > Champagne',
  winery: 'Moët & Chandon',
  winery_id: 'moet-and-chandon',
  varietal: 'Champagne',
  price: '622.89',
  vintage: '2005',
  type: 'Sparkling Wine',
  link: 'http://www.snooth.com/wine/dom-perignon-champagne-cuvee-vintage-2005/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/a/9/3/image_2860593_square.jpeg',
  snoothrank: 3.5,
  available: 1,
  num_merchants: 10,
  num_reviews: 2
},
{
  name: 'Roederer Cristal Rosé Champagne Brut',
    code: 'roederer-cristal-rose-champagne-brut-2000',
    region: 'France > Champagne',
    winery: 'Louis Roederer',
    winery_id: 'louis-roederer',
    varietal: 'Pinot Noir; Chardonnay',
    price: '499.92',
    vintage: '2000',
    type: 'Sparkling Wine',
    link: 'http://www.snooth.com/wine/roederer-cristal-rose-champagne-brut-2000/',
    tags: '',
    image: 'http://ei.isnooth.com/multimedia/f/2/6/image_1739108_square.jpeg',
    snoothrank: 'n/a',
    available: 0,
    num_merchants: 0,
    num_reviews: 1
},
{
  name: 'Screaming Eagle Cabernet Sauvignon',
    code: 'screaming-eagle-cabernet-sauvignon-2015',
    region: 'USA > California > Napa',
    winery: 'Screaming Eagle Winery',
    winery_id: 'screaming-eagle-winery',
    varietal: 'Cabernet Sauvignon',
    price: '15,000.00',
    vintage: '2015',
    type: '',
    link: 'http://www.snooth.com/wine/screaming-eagle-cabernet-sauvignon-2015/',
    tags: '',
    image: 'http://ei.isnooth.com/multimedia/3/7/e/image_4906626_square.jpeg',
    snoothrank: 'n/a',
    available: 1,
    num_merchants: 2,
    num_reviews: 0
},
{
  name: 'Schrader Cellars Cabernet Sauvignon Oakville Rbs Beckstoffer To-Kalon Vineyard',
    code: 'schrader-cellars-cabernet-sauvignon-oakville-rbs-beckstoffer-to-kalon-vineyard-2001',
    region: 'USA > California > Napa',
    winery: 'Schrader Cellars',
    winery_id: 'schrader-cellars',
    varietal: 'Cabernet Sauvignon',
    price: '3,199.97',
    vintage: '2001',
    type: 'Red Wine',
    link: 'http://www.snooth.com/wine/schrader-cellars-cabernet-sauvignon-oakville-rbs-beckstoffer-to-kalon-vineyard-2001/',
    tags: '',
    image: 'http://ei.isnooth.com/multimedia/d/9/a/image_511498_square.jpeg',
    snoothrank: 4.5,
    available: 0,
    num_merchants: 0,
    num_reviews: 7
},
{
  name: 'Dominus Napanook Napa',
  code: 'dominus-napanook-napa-2008',
  region: 'USA > California > Napa',
  winery: 'Dominus Estate',
  winery_id: 'dominus-estate',
  varietal: 'Cabernet Blends',
  price: '59.95',
  vintage: '2008',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/dominus-napanook-napa-2008/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/6/e/a/image_4183197_square.jpeg',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 8
},
{
  name: 'Gustavo Thrace Rutherford Cabernet Sauvignon',
  code: 'gustavo-thrace-rutherford-cabernet-sauvignon-2005',
  region: 'USA > California > Napa > Rutherford',
  winery: 'Gustavo Thrace',
  winery_id: 'gustavo-thrace',
  varietal: 'Cabernet Sauvignon',
  price: '59.99',
  vintage: '2005',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/gustavo-thrace-rutherford-cabernet-sauvignon-2005/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/b/0/a/image_932640_square.jpeg',
  snoothrank: 4.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 4
},
{
  name: 'Big Ass Cab -Wb90!',
  code: 'big-ass-cab-wb90-2007',
  region: 'USA > California > Napa',
  winery: 'Big Ass',
  winery_id: 'big-ass',
  varietal: 'Cabernet Sauvignon',
  price: '15.98',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/big-ass-cab-wb90-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/2/d/e/image_1155150_square.jpeg',
  snoothrank: 2.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 5
},
{
  name: 'Fisticuffs Cabernet Sauvignon Oakville',
  code: 'fisticuffs-cabernet-sauvignon-oakville-2007',
  region: 'USA > California > Napa County > Oakville',
  winery: 'Fisticuffs',
  winery_id: 'fisticuffs',
  varietal: 'Cabernet Sauvignon',
  price: '29.99',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/fisticuffs-cabernet-sauvignon-oakville-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/6/8/f/image_942238_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 6
},
{
  name: 'Benziger Family Winery Cabernet Sauvignon Napa Sonoma',
  code: 'benziger-family-winery-cabernet-sauvignon-napa-sonoma-2006',
  region: 'USA > California > Sonoma County > Sonoma Mountain',
  winery: 'Benziger Family Winery',
  winery_id: 'benziger-family-winery',
  varietal: 'Cabernet Sauvignon',
  price: '19.95',
  vintage: '2006',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/benziger-family-winery-cabernet-sauvignon-napa-sonoma-2006/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/b/1/1/image_950780_square.jpeg',
  snoothrank: 4,
  available: 0,
  num_merchants: 0,
  num_reviews: 6
},
{
  name: 'Joseph Carr Cabernet Sauvignon Napa Valley Red Hills',
  code: 'joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009',
  region: '',
  winery: 'Joseph Carr',
  winery_id: 'joseph-carr',
  varietal: 'Cabernet Sauvignon (75%); Merlot (15%); Cabernet Franc (10%)',
  price: '0.00',
  vintage: '2009',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/1/c/9/image_1230443_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 1
},
{
  name: 'Pont de Chevalier Cabernet Sauvignon Napa Valley le Chevalier',
  code: 'pont-de-chevalier-cabernet-sauvignon-napa-valley-le-chevalier-2007',
  region: 'USA > California > Sonoma County > Knights Valley',
  winery: 'Pont de Chevalier',
  winery_id: 'pont-de-chevalier',
  varietal: 'Cabernet Sauvignon (100%)',
  price: '79.69',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/pont-de-chevalier-cabernet-sauvignon-napa-valley-le-chevalier-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/d/5/b/image_1220133_square.jpeg',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 0
},
{
  name: 'Alta Napa Valley "Oso Malo" Cabernet Sauvignon',
  code: 'alta-napa-valley-oso-malo-cabernet-sauvignon-2011',
  region: 'USA > California > Napa County > Atlas Peak',
  winery: 'Alta Napa Valley',
  winery_id: 'alta-napa-valley',
  varietal: 'Cabernet Sauvignon',
  price: '42.00',
  msrp: '42.00',
  vintage: '2011',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/alta-napa-valley-oso-malo-cabernet-sauvignon-2011/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/1/5/c/image_2876278_square.png',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 0
},
{
  name: 'Alta Napa Valley "Oso Malo" Cabernet Sauvignon',
  code: 'alta-napa-valley-oso-malo-cabernet-sauvignon-2009',
  region: 'USA > California > Napa County > Atlas Peak',
  winery: 'Alta Napa Valley',
  winery_id: 'alta-napa-valley',
  varietal: 'Old vine Cabernet Sauvignon.  Clone 6.',
  price: '42.00',
  msrp: '42.00',
  vintage: '2009',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/alta-napa-valley-oso-malo-cabernet-sauvignon-2009/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/0/1/1/image_1608522_square.jpeg',
  snoothrank: 4,
  available: 0,
  num_merchants: 0,
  num_reviews: 1
},
{
  name: 'Avalon Cab',
  code: 'avalon-cab-2007',
  region: 'USA > California > Napa',
  winery: 'Avalon Wines',
  winery_id: 'avalon-wines',
  varietal: 'Cabernet Sauvignon',
  price: '14.54',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/avalon-cab-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/3/b/2/image_992059_square.jpeg',
  snoothrank: 3,
  available: 0,
  num_merchants: 0,
  num_reviews: 7
},
{
  name: 'Trinitas Red Bordeaux Blend Napa Valley Meritage',
  code: 'trinitas-red-bordeaux-blend-napa-valley-meritage-2008',
  region: 'USA > California > Napa > Oak Knoll',
  winery: 'Trinitas Cellars',
  winery_id: 'trinitas-cellars',
  varietal: '54% Cabernet, 19% Merlot, 17% Cabernet Franc, 10% Malbec   ',
  price: '42.99',
  vintage: '2008',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/trinitas-red-bordeaux-blend-napa-valley-meritage-2008/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/2/a/8/image_849646_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 3
}]


window.data = exampleData;