const exampleData = [{
  name: 'Conn Creek Cabernet Sauvignon Howell Mountain',
  code: 'conn-creek-cabernet-sauvignon-howell-mountain-2005',
  region: 'USA > California > Napa > Howell Mountain',
  winery: 'Conn Creek Winery',
  winery_id: 'conn-creek-winery',
  varietal: 'Cabernet Sauvignon',
  price: '26.00',
  vintage: '2005',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/conn-creek-cabernet-sauvignon-howell-mountain-2005/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/3/5/a/image_1201050_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 7
},
{
  name: 'Dominus Premier',
  code: 'dominus-premier-2007',
  region: 'USA > California > Napa',
  winery: 'Dominus Estate',
  winery_id: 'dominus-estate',
  varietal: 'Cabernet Sauvignon',
  price: '149.99',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/dominus-premier-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/7/d/d/image_1302514_square.jpeg',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 39
},
{
  name: 'Bevan Cellars Cabernet Sauvignon Oakville the Bab\'s Showket Vineyards',
  code: 'bevan-cellars-cabernet-sauvignon-oakville-the-babs-showket-vineyards-2009',
  region: 'USA > California > Napa County > Oakville',
  winery: 'Bevan Cellars',
  winery_id: 'bevan-cellars',
  varietal: 'Cabernet Sauvignon',
  price: '150.00',
  msrp: '150.00',
  vintage: '2009',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/bevan-cellars-cabernet-sauvignon-oakville-the-babs-showket-vineyards-2009/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/0/b/e/image_1640289_square.png',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 4
},
{
  name: 'Wine Spots Cabernet Sauvignon Napa Valley',
  code: 'wine-spots-cabernet-sauvignon-napa-valley-2007-1',
  region: 'USA > California > Napa',
  winery: 'Wine Spots Wines',
  winery_id: 'wine-spots-wines',
  varietal: 'Cabernet Sauvignon',
  price: '25.99',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/wine-spots-cabernet-sauvignon-napa-valley-2007-1/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/2/5/c/image_1221680_square.jpeg',
  snoothrank: 4,
  available: 0,
  num_merchants: 0,
  num_reviews: 4
},
{
  name: 'Dominus Napanook Napa',
  code: 'dominus-napanook-napa-2008',
  region: 'USA > California > Napa',
  winery: 'Dominus Estate',
  winery_id: 'dominus-estate',
  varietal: 'Cabernet Blends',
  price: '59.95',
  vintage: '2008',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/dominus-napanook-napa-2008/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/3/3/6/image_1609437_square.jpeg',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 8
},
{
  name: 'Gustavo Thrace Rutherford Cabernet Sauvignon',
  code: 'gustavo-thrace-rutherford-cabernet-sauvignon-2005',
  region: 'USA > California > Napa > Rutherford',
  winery: 'Gustavo Thrace',
  winery_id: 'gustavo-thrace',
  varietal: 'Cabernet Sauvignon',
  price: '59.99',
  vintage: '2005',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/gustavo-thrace-rutherford-cabernet-sauvignon-2005/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/b/0/a/image_932640_square.jpeg',
  snoothrank: 4.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 4
},
{
  name: 'Big Ass Cab -Wb90!',
  code: 'big-ass-cab-wb90-2007',
  region: 'USA > California > Napa',
  winery: 'Big Ass',
  winery_id: 'big-ass',
  varietal: 'Cabernet Sauvignon',
  price: '15.98',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/big-ass-cab-wb90-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/2/d/e/image_1155150_square.jpeg',
  snoothrank: 2.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 5
},
{
  name: 'Fisticuffs Cabernet Sauvignon Oakville',
  code: 'fisticuffs-cabernet-sauvignon-oakville-2007',
  region: 'USA > California > Napa County > Oakville',
  winery: 'Fisticuffs',
  winery_id: 'fisticuffs',
  varietal: 'Cabernet Sauvignon',
  price: '29.99',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/fisticuffs-cabernet-sauvignon-oakville-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/6/8/f/image_942238_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 6
},
{
  name: 'Benziger Family Winery Cabernet Sauvignon Napa Sonoma',
  code: 'benziger-family-winery-cabernet-sauvignon-napa-sonoma-2006',
  region: 'USA > California > Sonoma County > Sonoma Mountain',
  winery: 'Benziger Family Winery',
  winery_id: 'benziger-family-winery',
  varietal: 'Cabernet Sauvignon',
  price: '19.95',
  vintage: '2006',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/benziger-family-winery-cabernet-sauvignon-napa-sonoma-2006/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/b/1/1/image_950780_square.jpeg',
  snoothrank: 4,
  available: 0,
  num_merchants: 0,
  num_reviews: 6
},
{
  name: 'Joseph Carr Cabernet Sauvignon Napa Valley Red Hills',
  code: 'joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009',
  region: '',
  winery: 'Joseph Carr',
  winery_id: 'joseph-carr',
  varietal: 'Cabernet Sauvignon (75%); Merlot (15%); Cabernet Franc (10%)',
  price: '0.00',
  vintage: '2009',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/joseph-carr-cabernet-sauvignon-napa-valley-red-hills-2009/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/1/c/9/image_1230443_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 1
},
{
  name: 'Pont de Chevalier Cabernet Sauvignon Napa Valley le Chevalier',
  code: 'pont-de-chevalier-cabernet-sauvignon-napa-valley-le-chevalier-2007',
  region: 'USA > California > Sonoma County > Knights Valley',
  winery: 'Pont de Chevalier',
  winery_id: 'pont-de-chevalier',
  varietal: 'Cabernet Sauvignon (100%)',
  price: '79.69',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/pont-de-chevalier-cabernet-sauvignon-napa-valley-le-chevalier-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/d/5/b/image_1220133_square.jpeg',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 0
},
{
  name: 'Alta Napa Valley "Oso Malo" Cabernet Sauvignon',
  code: 'alta-napa-valley-oso-malo-cabernet-sauvignon-2011',
  region: 'USA > California > Napa County > Atlas Peak',
  winery: 'Alta Napa Valley',
  winery_id: 'alta-napa-valley',
  varietal: 'Cabernet Sauvignon',
  price: '42.00',
  msrp: '42.00',
  vintage: '2011',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/alta-napa-valley-oso-malo-cabernet-sauvignon-2011/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/1/5/c/image_2876278_square.png',
  snoothrank: 'n/a',
  available: 0,
  num_merchants: 0,
  num_reviews: 0
},
{
  name: 'Alta Napa Valley "Oso Malo" Cabernet Sauvignon',
  code: 'alta-napa-valley-oso-malo-cabernet-sauvignon-2009',
  region: 'USA > California > Napa County > Atlas Peak',
  winery: 'Alta Napa Valley',
  winery_id: 'alta-napa-valley',
  varietal: 'Old vine Cabernet Sauvignon.  Clone 6.',
  price: '42.00',
  msrp: '42.00',
  vintage: '2009',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/alta-napa-valley-oso-malo-cabernet-sauvignon-2009/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/0/1/1/image_1608522_square.jpeg',
  snoothrank: 4,
  available: 0,
  num_merchants: 0,
  num_reviews: 1
},
{
  name: 'Avalon Cab',
  code: 'avalon-cab-2007',
  region: 'USA > California > Napa',
  winery: 'Avalon Wines',
  winery_id: 'avalon-wines',
  varietal: 'Cabernet Sauvignon',
  price: '14.54',
  vintage: '2007',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/avalon-cab-2007/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/3/b/2/image_992059_square.jpeg',
  snoothrank: 3,
  available: 0,
  num_merchants: 0,
  num_reviews: 7
},
{
  name: 'Trinitas Red Bordeaux Blend Napa Valley Meritage',
  code: 'trinitas-red-bordeaux-blend-napa-valley-meritage-2008',
  region: 'USA > California > Napa > Oak Knoll',
  winery: 'Trinitas Cellars',
  winery_id: 'trinitas-cellars',
  varietal: '54% Cabernet, 19% Merlot, 17% Cabernet Franc, 10% Malbec   ',
  price: '42.99',
  vintage: '2008',
  type: 'Red Wine',
  link: 'http://www.snooth.com/wine/trinitas-red-bordeaux-blend-napa-valley-meritage-2008/',
  tags: '',
  image: 'http://ei.isnooth.com/multimedia/2/a/8/image_849646_square.jpeg',
  snoothrank: 3.5,
  available: 0,
  num_merchants: 0,
  num_reviews: 3
}]


window.data = exampleData;