Window.exampleData = [
  {
    "id": "546e64cf4c6458020000000d",
    "Name": "Duckhorn",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "",
    "Country": "USA",
    "Varietal": "Sauvignon Blanc",
    "vintage": "2013",
    "Style": "",
    "Type": "White"
  },
  {
    "id": "59455d175a126c5a6790a8b6",
    "Name": "Decoy Merlot",
    "Winery": "Duckhorn Vineyards",
    "Area": "Sonoma Valley",
    "Province": "",
    "Country": "USA",
    "Varietal": "Merlot",
    "vintage": "2013",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "552f5602d0259c030000000e",
    "Name": "Decoy",
    "Winery": "Duckhorn Vineyards",
    "Area": "Sonoma County",
    "Province": "",
    "Country": "USA",
    "Varietal": "Cabernet Sauvignon",
    "vintage": "2012",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "56e4ae4d1bff8c762d64dd99",
    "Name": "Decoy",
    "Winery": "Duckhorn Vineyards",
    "Area": "California",
    "Province": "",
    "Country": "USA",
    "Varietal": "Pinot Noir",
    "vintage": "2014",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "580e8752e12c5d7b522aff91",
    "Name": "Decoy",
    "Winery": "Duckhorn Vineyards",
    "Area": "Sonoma Valley",
    "Province": "",
    "Country": "USA",
    "Varietal": "Sauvignon Blanc",
    "vintage": "2014",
    "Style": "",
    "Type": "White"
  },
  {
    "id": "53597a22682acc020000af7c",
    "Name": "Russian River Valley",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "California",
    "Country": "USA",
    "Varietal": "Chardonnay",
    "vintage": "nv",
    "Style": "",
    "Type": "White"
  },
  {
    "id": "535977ba682acc0200009117",
    "Name": "Napa Valley",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "California",
    "Country": "USA",
    "Varietal": "Cabernet Sauvignon",
    "vintage": "nv",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "535974f8682acc020000625b",
    "Name": "Sonoma County",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "California",
    "Country": "USA",
    "Varietal": "Zinfandel",
    "vintage": "nv",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "535a60617dd3dc02000051dd",
    "Name": "Estate Grown Rector Creek",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "California",
    "Country": "USA",
    "Varietal": "Cabernet Sauvignon",
    "vintage": "nv",
    "Style": "",
    "Type": "Red"
  },
  {
    "id": "535a60d57dd3dc020000587d",
    "Name": "V Blend",
    "Winery": "Duckhorn Vineyards",
    "Area": "Napa Valley",
    "Province": "California",
    "Country": "USA",
    "Varietal": "Viognier, Chardonnay",
    "vintage": "nv",
    "Style": "",
    "Type": "White"
  }
]